
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 09 20:46:25 BRT 2012
//----------------------------------------------------

package codigoGerado;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 7;
  public static final int GE = 15;
  public static final int XOR = 8;
  public static final int DOUBLE = 45;
  public static final int LPAREN = 5;
  public static final int MINUS = 19;
  public static final int PRE = 26;
  public static final int RPAREN = 4;
  public static final int SEMICOLON = 42;
  public static final int NOT = 11;
  public static final int AND = 10;
  public static final int LT = 14;
  public static final int RCOL = 2;
  public static final int OR = 9;
  public static final int COMMA = 35;
  public static final int IMPLIES = 36;
  public static final int DOUBLEDOT = 39;
  public static final int DIV = 21;
  public static final int BAG = 22;
  public static final int COLLECTION = 25;
  public static final int PLUS = 18;
  public static final int IF = 28;
  public static final int DOT = 37;
  public static final int CONTEXT = 34;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int RBRACKET = 6;
  public static final int TRUE = 46;
  public static final int error = 1;
  public static final int PIPE = 41;
  public static final int NUMBER = 48;
  public static final int EQ = 12;
  public static final int NAME = 43;
  public static final int TIMES = 20;
  public static final int ARROW = 38;
  public static final int COLON = 32;
  public static final int ENDIF = 31;
  public static final int ELSE = 30;
  public static final int POST = 27;
  public static final int THEN = 29;
  public static final int NE = 17;
  public static final int STRING = 44;
  public static final int LCOL = 3;
  public static final int SEQUENCE = 24;
  public static final int AT = 40;
  public static final int FALSE = 47;
  public static final int GT = 13;
  public static final int DOUBLECOLON = 33;
  public static final int SET = 23;
}

