
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 14 10:36:35 BRT 2012
//----------------------------------------------------

package codigoGerado;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 5;
  public static final int GE = 13;
  public static final int XOR = 6;
  public static final int DOUBLE = 44;
  public static final int INTEGER = 43;
  public static final int LPAREN = 3;
  public static final int MINUS = 17;
  public static final int PRE = 24;
  public static final int RPAREN = 2;
  public static final int SEMICOLON = 40;
  public static final int NOT = 9;
  public static final int AND = 8;
  public static final int LT = 12;
  public static final int OR = 7;
  public static final int COMMA = 33;
  public static final int IMPLIES = 34;
  public static final int DOUBLEDOT = 37;
  public static final int DIV = 19;
  public static final int BAG = 20;
  public static final int COLLECTION = 23;
  public static final int PLUS = 16;
  public static final int IF = 26;
  public static final int DOT = 35;
  public static final int CONTEXT = 32;
  public static final int LE = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 4;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int PIPE = 39;
  public static final int EQ = 10;
  public static final int NAME = 41;
  public static final int TIMES = 18;
  public static final int ARROW = 36;
  public static final int COLON = 30;
  public static final int ENDIF = 29;
  public static final int ELSE = 28;
  public static final int POST = 25;
  public static final int THEN = 27;
  public static final int NE = 15;
  public static final int STRING = 42;
  public static final int SEQUENCE = 22;
  public static final int AT = 38;
  public static final int FALSE = 46;
  public static final int GT = 11;
  public static final int DOUBLECOLON = 31;
  public static final int SET = 21;
}

