
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 14 20:37:49 BRT 2012
//----------------------------------------------------

package codigoGerado;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 5;
  public static final int GE = 13;
  public static final int XOR = 6;
  public static final int DOUBLE = 37;
  public static final int INTEGER = 36;
  public static final int LPAREN = 3;
  public static final int INV = 21;
  public static final int MINUS = 17;
  public static final int RPAREN = 2;
  public static final int NOT = 9;
  public static final int AND = 8;
  public static final int LT = 12;
  public static final int OR = 7;
  public static final int COMMA = 28;
  public static final int IMPLIES = 29;
  public static final int DIV = 19;
  public static final int COLLECTION = 20;
  public static final int PLUS = 16;
  public static final int IF = 22;
  public static final int DOT = 30;
  public static final int CONTEXT = 27;
  public static final int LE = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 4;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int SELF = 34;
  public static final int PIPE = 32;
  public static final int EQ = 10;
  public static final int NAME = 33;
  public static final int TIMES = 18;
  public static final int ARROW = 31;
  public static final int COLON = 26;
  public static final int ENDIF = 25;
  public static final int ELSE = 24;
  public static final int THEN = 23;
  public static final int NE = 15;
  public static final int STRING = 35;
  public static final int FALSE = 39;
  public static final int GT = 11;
}

